mqtt:
  client:
    protocol: 4      # MQTTv311
    client_id: "nano"
  connection:
    host: a2j9cqazhtf0ii-ats.iot.ap-southeast-1.amazonaws.com
    port: 8883
    keepalive: 60
  private_path: device/001
#serializer: json:dumps
#deserializer: json:loads
bridge:
  # ping pong
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:Bool
    topic_from: /ping
    topic_to: ping
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:Bool
    topic_from: ping
    topic_to: /pong
  # schedule
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:String
    topic_from: schedule
    topic_to: /simple_navigation_mqtt/schedule
  # pose
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: move_base_msgs.msg:MoveBaseActionGoal
    topic_from: pose
    topic_to: /mqtt/movebase/goal 
  # velocity
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: geometry_msgs.msg:Twist
    topic_from: velocity
    topic_to: /mqtt/cmd_vel
  # location
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:String
    topic_from: location
    topic_to: /location
  # echo back
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: slamware_ros_sdk.msg:RobotBasicState
    topic_from: /slamware_ros_sdk_server_node/robot_basic_state
    topic_to: status
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:String
    topic_from: movement
    topic_to: /topic_1
  # private path
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:String
    topic_from: /private/echo
    topic_to: ~/echo
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:String
    topic_from: ~/echo
    topic_to: /private/back
